### ISSUE TITLE
A senhas dos usuários não podem ser 'recuperadas'

### ISSUE THREAD

**Issue by andre-filho** [MPS-FGA/Avaleasy-backend#12]
A atual implementação da encriptação das senhas impede da mesma ser refeita ou recuperada

**Comment by matheusbsilva** [comment]
A senha não deve ser restaurada, ou seja descriptografada. Caso o usuário perca a senha a melhor solução é enviar para o email dele um link no qual ele possa criar uma nova senha. Acho que esses materiais podem ajudar:
[Password Reset Using JWT](https://www.codementor.io/olatundegaruba/password-reset-using-jwt-ag2pmlck0)
[How To Implement Password Reset In Node.js](http://sahatyalkabov.com/how-to-implement-password-reset-in-nodejs/)

**Comment by andre-filho** [comment]
não era esse o problema, acho que expliquei errado. Veja o pr #13 pfvr
