### ISSUE TITLE
Dependencias não estão sendo mantidas após o desligamento do container

### ISSUE THREAD

**Issue by andre-filho** [MPS-FGA/Avaleasy-backend#14]
Certas dependencias, como o `nodemon` e o `jsonwebtoken` não estão sendo mantidas no yarn mesmo com a instalação com o `--save`

**Comment by alaxalves** [comment]
@matheusbsilva Apenas mapear o yarn.lock e o package.json como volume resolve esse problema??

**Comment by alaxalves** [comment]
@andre-filho Como eu reproduzo esse erro?

**Comment by andre-filho** [comment]
Sobe o container lá na branco do login

**Comment by alaxalves** [comment]
@andre-filho Consegui resolver, está na branch  `9#login`. Execute `docker-compose --build` e pronto!

**Comment by alaxalves** [comment]
@andre-filho Se der tudo certo já vem e fecha a issue aqui.

**Comment by andre-filho** [comment]
funcionou agr, a solução terá merge juntamente com a funcionalidade do login

**Comment by alaxalves** [comment]
Resolvido em https://github.com/MPS-FGA/Avaleasy-backend/pull/19
