### ISSUE TITLE
Realizar login

### ISSUE THREAD

**Issue by matheusbsilva** [MPS-FGA/Avaleasy-backend#9]
Feature: #5 [Autenticação de professor](https://github.com/MPS-FGA/Avaleasy-app/issues/5)

Eu como professor desejo realizar o login para me autenticar na aplicação.

Critérios de aceitação:
- [x] Campo para inserir e-mail
- [x] Campo para inserir senha
- [x] Testes

**Comment by alaxalves** [comment]
Resolvido em: https://github.com/MPS-FGA/Avaleasy-backend/pull/13
